### ISSUE TITLE
OBI concretized as

### ISSUE THREAD

**Issue by robgur** [tucotuco/bco#43]
Need to deal with 'is concretized as' from OBI - repeat from RO.   Delete these from OBI_imports.

**Comment by rlwalls2008** [comment]
Also remove BFO:is concretized as in favor of RO relation. 

Neither are being used in BCO, but obi uses concretizes to say:
information content entity 'is concretized as' some  ('information carrier' and ('inheres in' some 'material information bearer')). 
We will need to replace this relation by hand in obi-bco-imports.owl, in the hopes that when the new OBI comes out, it will use the RO relation.

**Comment by rlwalls2008** [comment]
Steps to remove this by hand (documented in OBI_Ontofox.txt):
1. remove inverse relation between BFO:concretizes and BFO:is concretized as 
2. delete BFO:concretizes and BFO:is concretized as
3. update logical definitions of information content entity and primary structure of DNA macromolecule to use RO:is concretized as instead of BFO (will need to copy from OBI)
4. update logical definitions of material information bearer and planned process to use RO:concretizes instead of BFO (will need to copy from OBI)

**Comment by rlwalls2008** [comment]
Note that the changes in steps 6 and 7 above are saved in BCO, not obi-bco-imports, so they will need to be removed once there is a new obi import.

**Comment by tucotuco** [comment]
Should the documentation go in our wiki also?

**Comment by rlwalls2008** [comment]
I think it is enough to have it here and in the OBI-Ontofox.txt file. The text file is the real key to what gets imported and done to the import file. I don't really want a wiki page for this, because I hope it is the last time I will have to do it.
