### ISSUE TITLE
change IRIs of import ontologies

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#60]
to the form:
http://purl.obolibrary.org/obo/bco/src/ontology/import_ontology_name.owl 
in the editors' version.

**Comment by rlwalls2008** [comment]
Changed IRIs for dwcterms.owl and obi_bco_import.owl.

**Comment by rlwalls2008** [comment]
Even though it worked yesterday when I first tried it, this will not work today. If we leave the purls as recommended, when you try to open bco.owl from the raw source url, Protege cannot find the imports, because it wants to redirect to the import ontologies' IRIs, instead of their location. For now I am just going to move them back to the github urls in the development version.

**Comment by cmungall** [comment]
Is this P5 or P4? The recommendation is to go with 5.

purl.obolibrary.org doesn't appear to be working now, not sure why

**Comment by cmungall** [comment]
Scratch that it works, there was a typo in the url above

http://purl.obolibary.org/obo/bco/src/ontology/import_ontology_name.owl 
==>
http://purl.obolibrary.org/obo/bco/src/ontology/import_ontology_name.owl 

I think the issue is that it redirects here: https://raw.githubusercontent.com/tucotuco/bco/master/src/ontology/import_ontology_name.owl 

but there is nothing there

**Comment by rlwalls2008** [comment]
P5, but I think I figured out why I was having problems. We were not versioning the catalog file in the src/ontology directory. I added it, but Now I am at my folks for dinner :)

Will try it out later. 

Ramona

Enviado de Baja Arizona.
